INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (2, 'BANAMEX', 'Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (6, 'BANCOMEXT', 'Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (9, 'BANOBRAS', 'Banco Nacional de Obras y Servicios Públicos, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (12, 'BBVA BANCOMER', 'BBVA Bancomer, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA Bancomer', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (14, 'SANTANDER', 'Banco Santander (México), S.A., Institución de Banca Múltiple, Grupo Financiero Santander', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (19, 'BANJERCITO', 'Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (21, 'HSBC', 'HSBC México, S.A., institución De Banca Múltiple, Grupo Financiero HSBC', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (30, 'BAJIO', 'Banco del Bajío, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (32, 'IXE', 'IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (36, 'INBURSA', 'Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (37, 'INTERACCIONES', 'Banco Interacciones, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (42, 'MIFEL', 'Banca Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (44, 'SCOTIABANK', 'Scotiabank Inverlat, S.A.', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (58, 'BANREGIO', 'Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo Financiero', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (59, 'INVEX', 'Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (60, 'BANSI', 'Bansi, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (62, 'AFIRME', 'Banca Afirme, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (72, 'BANORTE', 'Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (102, 'THE ROYAL BANK', 'The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (103, 'AMERICAN EXPRESS', 'American Express Bank (México), S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (106, 'BAMSA', 'Bank of America México, S.A., Institución de Banca Múltiple, Grupo Financiero Bank of America', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (108, 'TOKYO', 'Bank of Tokyo-Mitsubishi UFJ (México), S.A.', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (110, 'JP MORGAN', 'Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (112, 'BMONEX', 'Banco Monex, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (113, 'VE POR MAS', 'Banco Ve Por Mas, S.A. Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (116, 'ING', 'ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (124, 'DEUTSCHE', 'Deutsche Bank México, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (126, 'CREDIT SUISSE', 'Banco Credit Suisse (México), S.A. Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (127, 'AZTECA', 'Banco Azteca, S.A. Institución de Banca Múltiple.', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (128, 'AUTOFIN', 'Banco Autofin México, S.A. Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (129, 'BARCLAYS', 'Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (130, 'COMPARTAMOS', 'Banco Compartamos, S.A., Institución de Banca Múltiple', '1');
INSERT INTO cat_bancos (`cat_bancos_id`, `nombre`, `descripcion`, `estatus`) VALUES (131, 'BANCO FAMSA', 'Banco Ahorro Famsa, S.A., Institución de Banca Múltiple', '1');

